version: '3.8'

services:
  app:
    image: uygar00/selenium-aylik-rapor:latest
    restart: "no"
    secrets:
      - mail_email
      - mail_pass
      - txps_email
      - txps_pass

secrets:
  mail_email:
    external: true
  mail_pass:
    external: true
  txps_email:
    external: true
  txps_pass:
    external: true